services:
  - type: web
    name: todo-list-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: todo-data
      mountPath: /opt/render/project/src
      sizeGB: 1
